apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  artifacts:
    - image: omrilevy0197/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: omrilevy0197/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: omrilevy0197/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: omrilevy0197/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: omrilevy0197/payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: omrilevy0197/ticketing-client
      context: client
      sync:
        infer:
          - src/**/*.ts
          - src/**/*.tsx
      docker:
        dockerfile: Dockerfile
  local:
    push: false

