name: tests-payments

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      JWT_SECRET: test-jwt-secret
      STRIPE_SECRET: sk_test_51J5mAKIRdzKR5zq4GLyTTy2zL7YgVOnXgDwXyLPcRFJo8TwEgafMKJ8kkI1hub0Bkdrq9k1GVRgEExqmILuOOkqc00YbsVXoCX
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
      
